from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 837)
        MainWindow.setStyleSheet("\n"
"QMainWindow,QWidget{background:#262A2E;color:#F2F4F5;font-family:\'Segoe UI\';}\n"
"QGroupBox{background:#2F353B;border:1px solid #4B5663;border-radius:6px;\n"
"margin-top:12px;padding-top:12px;color:#7F8A96;font-weight:bold;}\n"
"QGroupBox::title{subcontrol-origin:margin;left:10px;padding:0 4px;}\n"
"QLabel{color:#00FFE5;background:transparent;font-weight:bold;}\n"
"QLineEdit,QTextEdit,QComboBox{\n"
" background:#1F2429;border:1px solid #4B5663;color:white;padding:6px;}\n"
"QTextEdit{border:2px solid #00FFE5;}\n"
"QPushButton{\n"
" background:#2F353B;border:2px solid #00FFE5;color:#00FFE5;\n"
" min-height:34px;font-weight:bold;border-radius:4px;}\n"
"QPushButton:hover{background:#374049;}\n"
"QTableWidget{\n"
" background:#1F2429;border:1px solid #4B5663;\n"
" gridline-color:#4B5663;color:white;}\n"
"QHeaderView::section{\n"
" background:#2F353B;color:#00FFE5;padding:6px;border:none;}\n"
"QLabel#lblTitle{font-size: 42px; color:#00FFE5; margin-bottom:10px;}\n"
"QLabel#lblSubtitle{font-size: 18px; color:#F2F4F5; margin-bottom:30px;}\n"
"QMenuBar { background-color: #1F2429; color: white; border-bottom: 1px solid #4B5663;}\n"
"QMenuBar::item { background-color: transparent; padding: 6px 14px; }\n"
"QMenuBar::item:selected { background-color: #374049; color: #00FFE5; }\n"
"QMenu { background-color: #2F353B; color: white; border: 1px solid #4B5663; }\n"
"QMenu::item { padding: 8px 24px; }\n"
"QMenu::item:selected { background-color: #374049; color: #00FFE5; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_landing = QtWidgets.QWidget()
        self.page_landing.setObjectName("page_landing")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_landing)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lblTitle = QtWidgets.QLabel(parent=self.page_landing)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=self.page_landing)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_2.addWidget(self.lblSubtitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnGoDashboard = QtWidgets.QPushButton(parent=self.page_landing)
        self.btnGoDashboard.setMinimumSize(QtCore.QSize(200, 38))
        self.btnGoDashboard.setObjectName("btnGoDashboard")
        self.horizontalLayout.addWidget(self.btnGoDashboard)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnBukanAdmin = QtWidgets.QPushButton(parent=self.page_landing)
        self.btnBukanAdmin.setMinimumSize(QtCore.QSize(200, 38))
        self.btnBukanAdmin.setStyleSheet("QPushButton { background-color: #2F353B; color: #E63946; font-weight: bold; border-radius: 4px; border: 2px solid #E63946; } QPushButton:hover { background-color: #374049; }")
        self.btnBukanAdmin.setObjectName("btnBukanAdmin")
        self.horizontalLayout_2.addWidget(self.btnBukanAdmin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page_landing)
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.gridLayout = QtWidgets.QGridLayout(self.page_dashboard)
        self.gridLayout.setObjectName("gridLayout")
        self.lblDashboardTitle = QtWidgets.QLabel(parent=self.page_dashboard)
        self.lblDashboardTitle.setStyleSheet("font-size: 28px; color: #00FFE5; margin-bottom: 15px; font-weight: bold;")
        self.lblDashboardTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDashboardTitle.setObjectName("lblDashboardTitle")
        self.gridLayout.addWidget(self.lblDashboardTitle, 0, 0, 1, 2)
        self.groupForm = QtWidgets.QGroupBox(parent=self.page_dashboard)
        self.groupForm.setObjectName("groupForm")
        self.formLayout = QtWidgets.QFormLayout(self.groupForm)
        self.formLayout.setObjectName("formLayout")
        self.lblNama = QtWidgets.QLabel(parent=self.groupForm)
        self.lblNama.setObjectName("lblNama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNama)
        self.editNama096 = QtWidgets.QLineEdit(parent=self.groupForm)
        self.editNama096.setObjectName("editNama096")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editNama096)
        self.lblJam = QtWidgets.QLabel(parent=self.groupForm)
        self.lblJam.setObjectName("lblJam")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblJam)
        self.editJaminan096 = QtWidgets.QLineEdit(parent=self.groupForm)
        self.editJaminan096.setObjectName("editJaminan096")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editJaminan096)
        self.lblTanggalMulai = QtWidgets.QLabel(parent=self.groupForm)
        self.lblTanggalMulai.setObjectName("lblTanggalMulai")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTanggalMulai)
        self.dateMulai096 = QtWidgets.QDateEdit(parent=self.groupForm)
        self.dateMulai096.setCalendarPopup(True)
        self.dateMulai096.setObjectName("dateMulai096")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateMulai096)
        self.lblTanggalSelesai = QtWidgets.QLabel(parent=self.groupForm)
        self.lblTanggalSelesai.setObjectName("lblTanggalSelesai")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTanggalSelesai)
        self.dateSelesai096 = QtWidgets.QDateEdit(parent=self.groupForm)
        self.dateSelesai096.setCalendarPopup(True)
        self.dateSelesai096.setObjectName("dateSelesai096")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateSelesai096)
        self.lblWa = QtWidgets.QLabel(parent=self.groupForm)
        self.lblWa.setObjectName("lblWa")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblWa)
        self.editWa096 = QtWidgets.QLineEdit(parent=self.groupForm)
        self.editWa096.setObjectName("editWa096")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editWa096)
        self.lblAlamat = QtWidgets.QLabel(parent=self.groupForm)
        self.lblAlamat.setObjectName("lblAlamat")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblAlamat)
        self.textAlamat096 = QtWidgets.QTextEdit(parent=self.groupForm)
        self.textAlamat096.setObjectName("textAlamat096")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textAlamat096)
        self.btnSimpan096 = QtWidgets.QPushButton(parent=self.groupForm)
        self.btnSimpan096.setObjectName("btnSimpan096")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnSimpan096)
        self.gridLayout.addWidget(self.groupForm, 1, 0, 1, 1)
        self.groupTable = QtWidgets.QGroupBox(parent=self.page_dashboard)
        self.groupTable.setObjectName("groupTable")
        self.vbox = QtWidgets.QVBoxLayout(self.groupTable)
        self.vbox.setObjectName("vbox")
        self.tableWidget096 = QtWidgets.QTableWidget(parent=self.groupTable)
        self.tableWidget096.setObjectName("tableWidget096")
        self.tableWidget096.setColumnCount(5)
        self.tableWidget096.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget096.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget096.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget096.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget096.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget096.setHorizontalHeaderItem(4, item)
        self.vbox.addWidget(self.tableWidget096)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        self.btnEdit096 = QtWidgets.QPushButton(parent=self.groupTable)
        self.btnEdit096.setObjectName("btnEdit096")
        self.buttons.addWidget(self.btnEdit096)
        self.btnDelete096 = QtWidgets.QPushButton(parent=self.groupTable)
        self.btnDelete096.setObjectName("btnDelete096")
        self.buttons.addWidget(self.btnDelete096)
        self.vbox.addLayout(self.buttons)
        self.gridLayout.addWidget(self.groupTable, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_dashboard)
        self.page_membership = QtWidgets.QWidget()
        self.page_membership.setObjectName("page_membership")
        self.gridLayout_membership = QtWidgets.QGridLayout(self.page_membership)
        self.gridLayout_membership.setObjectName("gridLayout_membership")
        self.lblMembershipTitle = QtWidgets.QLabel(parent=self.page_membership)
        self.lblMembershipTitle.setStyleSheet("font-size: 28px; color: #00FFE5; margin-bottom: 15px; font-weight: bold;")
        self.lblMembershipTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMembershipTitle.setObjectName("lblMembershipTitle")
        self.gridLayout_membership.addWidget(self.lblMembershipTitle, 0, 0, 1, 2)
        self.groupMembershipForm = QtWidgets.QGroupBox(parent=self.page_membership)
        self.groupMembershipForm.setObjectName("groupMembershipForm")
        self.formLayout_membership = QtWidgets.QFormLayout(self.groupMembershipForm)
        self.formLayout_membership.setObjectName("formLayout_membership")
        self.lblPelanggan = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblPelanggan.setObjectName("lblPelanggan")
        self.formLayout_membership.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPelanggan)
        self.opsiPelanggan064 = QtWidgets.QComboBox(parent=self.groupMembershipForm)
        self.opsiPelanggan064.setObjectName("opsiPelanggan064")
        self.formLayout_membership.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.opsiPelanggan064)
        self.lblTipePS = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblTipePS.setObjectName("lblTipePS")
        self.formLayout_membership.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTipePS)
        self.opsiTipePS064 = QtWidgets.QComboBox(parent=self.groupMembershipForm)
        self.opsiTipePS064.setObjectName("opsiTipePS064")
        self.opsiTipePS064.addItem("")
        self.opsiTipePS064.addItem("")
        self.opsiTipePS064.addItem("")
        self.opsiTipePS064.addItem("")
        self.formLayout_membership.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.opsiTipePS064)
        self.lblDiskonTier = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblDiskonTier.setObjectName("lblDiskonTier")
        self.formLayout_membership.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblDiskonTier)
        self.opsiTier064 = QtWidgets.QComboBox(parent=self.groupMembershipForm)
        self.opsiTier064.setObjectName("opsiTier064")
        self.opsiTier064.addItem("")
        self.opsiTier064.addItem("")
        self.opsiTier064.addItem("")
        self.opsiTier064.addItem("")
        self.opsiTier064.addItem("")
        self.formLayout_membership.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.opsiTier064)
        self.lblTglGabung = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblTglGabung.setObjectName("lblTglGabung")
        self.formLayout_membership.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTglGabung)
        self.memberGabung064 = QtWidgets.QDateEdit(parent=self.groupMembershipForm)
        self.memberGabung064.setCalendarPopup(True)
        self.memberGabung064.setObjectName("memberGabung064")
        self.formLayout_membership.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.memberGabung064)
        self.lblIncludeTV = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblIncludeTV.setObjectName("lblIncludeTV")
        self.formLayout_membership.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblIncludeTV)
        self.lblJasaAntar = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblJasaAntar.setObjectName("lblJasaAntar")
        self.formLayout_membership.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblJasaAntar)
        self.lblJarak = QtWidgets.QLabel(parent=self.groupMembershipForm)
        self.lblJarak.setObjectName("lblJarak")
        self.formLayout_membership.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblJarak)
        self.jarak064 = QtWidgets.QSpinBox(parent=self.groupMembershipForm)
        self.jarak064.setMaximum(100)
        self.jarak064.setObjectName("jarak064")
        self.formLayout_membership.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.jarak064)
        self.simpanMember064 = QtWidgets.QPushButton(parent=self.groupMembershipForm)
        self.simpanMember064.setObjectName("simpanMember064")
        self.formLayout_membership.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.simpanMember064)
        self.btnMaster064 = QtWidgets.QPushButton(parent=self.groupMembershipForm)
        self.btnMaster064.setObjectName("btnMaster064")
        self.formLayout_membership.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnMaster064)
        self.cekTV064 = QtWidgets.QCheckBox(parent=self.groupMembershipForm)
        self.cekTV064.setObjectName("cekTV064")
        self.formLayout_membership.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cekTV064)
        self.kurir064 = QtWidgets.QCheckBox(parent=self.groupMembershipForm)
        self.kurir064.setObjectName("kurir064")
        self.formLayout_membership.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.kurir064)
        self.gridLayout_membership.addWidget(self.groupMembershipForm, 1, 0, 1, 1)
        self.groupMembershipTable = QtWidgets.QGroupBox(parent=self.page_membership)
        self.groupMembershipTable.setObjectName("groupMembershipTable")
        self.vbox_membership = QtWidgets.QVBoxLayout(self.groupMembershipTable)
        self.vbox_membership.setObjectName("vbox_membership")
        self.tableMembership064 = QtWidgets.QTableWidget(parent=self.groupMembershipTable)
        self.tableMembership064.setObjectName("tableMembership064")
        self.tableMembership064.setColumnCount(7)
        self.tableMembership064.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMembership064.setHorizontalHeaderItem(6, item)
        self.vbox_membership.addWidget(self.tableMembership064)
        self.buttons_membership = QtWidgets.QHBoxLayout()
        self.buttons_membership.setObjectName("buttons_membership")
        self.editMember064 = QtWidgets.QPushButton(parent=self.groupMembershipTable)
        self.editMember064.setObjectName("editMember064")
        self.buttons_membership.addWidget(self.editMember064)
        self.hpsMember064 = QtWidgets.QPushButton(parent=self.groupMembershipTable)
        self.hpsMember064.setObjectName("hpsMember064")
        self.buttons_membership.addWidget(self.hpsMember064)
        self.vbox_membership.addLayout(self.buttons_membership)
        self.gridLayout_membership.addWidget(self.groupMembershipTable, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_membership)
        self.page_transaksi = QtWidgets.QWidget()
        self.page_transaksi.setObjectName("page_transaksi")
        self.verticalLayout_transaksi = QtWidgets.QVBoxLayout(self.page_transaksi)
        self.verticalLayout_transaksi.setObjectName("verticalLayout_transaksi")
        self.lblTransaksiTitle = QtWidgets.QLabel(parent=self.page_transaksi)
        self.lblTransaksiTitle.setStyleSheet("font-size: 28px; color: #00FFE5; margin-bottom: 15px; font-weight: bold;")
        self.lblTransaksiTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTransaksiTitle.setObjectName("lblTransaksiTitle")
        self.verticalLayout_transaksi.addWidget(self.lblTransaksiTitle)
        self.groupTransaksiTable = QtWidgets.QGroupBox(parent=self.page_transaksi)
        self.groupTransaksiTable.setObjectName("groupTransaksiTable")
        self.vbox_transaksi_table = QtWidgets.QVBoxLayout(self.groupTransaksiTable)
        self.vbox_transaksi_table.setObjectName("vbox_transaksi_table")
        self.tableTransaksi = QtWidgets.QTableWidget(parent=self.groupTransaksiTable)
        self.tableTransaksi.setObjectName("tableTransaksi")
        self.tableTransaksi.setColumnCount(4)
        self.tableTransaksi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransaksi.setHorizontalHeaderItem(3, item)
        self.vbox_transaksi_table.addWidget(self.tableTransaksi)
        self.buttons_transaksi = QtWidgets.QHBoxLayout()
        self.buttons_transaksi.setObjectName("buttons_transaksi")
        self.btnKembaliTransaksi = QtWidgets.QPushButton(parent=self.groupTransaksiTable)
        self.btnKembaliTransaksi.setObjectName("btnKembaliTransaksi")
        self.buttons_transaksi.addWidget(self.btnKembaliTransaksi)
        self.btnEditPelangganDb = QtWidgets.QPushButton(parent=self.groupTransaksiTable)
        self.btnEditPelangganDb.setObjectName("btnEditPelangganDb")
        self.buttons_transaksi.addWidget(self.btnEditPelangganDb)
        self.btnEditMembershipDb = QtWidgets.QPushButton(parent=self.groupTransaksiTable)
        self.btnEditMembershipDb.setObjectName("btnEditMembershipDb")
        self.buttons_transaksi.addWidget(self.btnEditMembershipDb)
        self.vbox_transaksi_table.addLayout(self.buttons_transaksi)
        self.verticalLayout_transaksi.addWidget(self.groupTransaksiTable)
        self.stackedWidget.addWidget(self.page_transaksi)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 28))
        self.menubar.setObjectName("menubar")
        self.menuApp = QtWidgets.QMenu(parent=self.menubar)
        self.menuApp.setObjectName("menuApp")
        self.menuManage = QtWidgets.QMenu(parent=self.menubar)
        self.menuManage.setObjectName("menuManage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLanding_Page = QtGui.QAction(parent=MainWindow)
        self.actionLanding_Page.setObjectName("actionLanding_Page")
        self.actionDashboard = QtGui.QAction(parent=MainWindow)
        self.actionDashboard.setObjectName("actionDashboard")
        self.actionMembership = QtGui.QAction(parent=MainWindow)
        self.actionMembership.setObjectName("actionMembership")
        self.actionTransaksi = QtGui.QAction(parent=MainWindow)
        self.actionTransaksi.setObjectName("actionTransaksi")
        self.menuApp.addAction(self.actionLanding_Page)
        self.menuManage.addAction(self.actionDashboard)
        self.menuManage.addAction(self.actionMembership)
        self.menuManage.addAction(self.actionTransaksi)
        self.menubar.addAction(self.menuApp.menuAction())
        self.menubar.addAction(self.menuManage.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplikasi RentalPS"))
        self.lblTitle.setText(_translate("MainWindow", "APLIKASI JAWARAPS"))
        self.lblSubtitle.setText(_translate("MainWindow", "Disclaimer! Program ini milik JawaraPS, Program ini hanya boleh diakses pemilik/pengurus JawaraPS saja"))
        self.btnGoDashboard.setText(_translate("MainWindow", "KLIK KALAU KAMU ADMIN"))
        self.btnBukanAdmin.setText(_translate("MainWindow", "KLIK! JIKA KAMU BUKAN ADMIN"))
        self.lblDashboardTitle.setText(_translate("MainWindow", "DASHBOARD DATA MEMBER"))
        self.groupForm.setTitle(_translate("MainWindow", "MASUKKAN DATA DISINI"))
        self.lblNama.setText(_translate("MainWindow", "Nama"))
        self.lblJam.setText(_translate("MainWindow", "Jaminan"))
        self.lblTanggalMulai.setText(_translate("MainWindow", "Tanggal Rental"))
        self.lblTanggalSelesai.setText(_translate("MainWindow", "Tanggal Berakhir"))
        self.lblWa.setText(_translate("MainWindow", "No WhatsApp"))
        self.lblAlamat.setText(_translate("MainWindow", "Alamat"))
        self.btnSimpan096.setText(_translate("MainWindow", "SIMPAN"))
        self.groupTable.setTitle(_translate("MainWindow", "DATA LENGKAP MEMBER JAWARAPS"))
        item = self.tableWidget096.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableWidget096.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jaminan"))
        item = self.tableWidget096.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Member"))
        item = self.tableWidget096.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "WhatsApp"))
        item = self.tableWidget096.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat"))
        self.btnEdit096.setText(_translate("MainWindow", "EDIT"))
        self.btnDelete096.setText(_translate("MainWindow", "DELETE"))
        self.lblMembershipTitle.setText(_translate("MainWindow", "DATA MEMBERSHIP"))
        self.groupMembershipForm.setTitle(_translate("MainWindow", "DAFTARKAN MEMBER BARU DISINI"))
        self.lblPelanggan.setText(_translate("MainWindow", "Pilih Pelanggan"))
        self.lblTipePS.setText(_translate("MainWindow", "Tipe PS"))
        self.opsiTipePS064.setItemText(0, _translate("MainWindow", "PS2 (Rp 10.000/hari)"))
        self.opsiTipePS064.setItemText(1, _translate("MainWindow", "PS3 (Rp 20.000/hari)"))
        self.opsiTipePS064.setItemText(2, _translate("MainWindow", "PS4 (Rp 30.000/hari)"))
        self.opsiTipePS064.setItemText(3, _translate("MainWindow", "PS5 (Rp 40.000/hari)"))
        self.lblDiskonTier.setText(_translate("MainWindow", "Pilih Tier/Diskon"))
        self.opsiTier064.setItemText(0, _translate("MainWindow", "No Member - 0%"))
        self.opsiTier064.setItemText(1, _translate("MainWindow", "Bronze - 10%"))
        self.opsiTier064.setItemText(2, _translate("MainWindow", "Silver - 20%"))
        self.opsiTier064.setItemText(3, _translate("MainWindow", "Gold - 30%"))
        self.opsiTier064.setItemText(4, _translate("MainWindow", "Platinum - 40%"))
        self.lblTglGabung.setText(_translate("MainWindow", "Tanggal Transaksi"))
        self.lblIncludeTV.setText(_translate("MainWindow", "Include TV?"))
        self.lblJasaAntar.setText(_translate("MainWindow", "Jasa Antar"))
        self.lblJarak.setText(_translate("MainWindow", "Jarak (KM)"))
        self.simpanMember064.setText(_translate("MainWindow", "SIMPAN"))
        self.btnMaster064.setText(_translate("MainWindow", "LIHAT TRANSAKSI"))
        self.cekTV064.setText(_translate("MainWindow", "Ya (+Rp 15.000/hari)"))
        self.kurir064.setText(_translate("MainWindow", "Pakai Jasa Pengantaran"))
        self.groupMembershipTable.setTitle(_translate("MainWindow", "ABSEN YANG SUDAH MEMBERSHIP"))
        item = self.tableMembership064.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pilih"))
        item = self.tableMembership064.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pelanggan"))
        item = self.tableMembership064.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tier/Diskon"))
        item = self.tableMembership064.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipe PS"))
        item = self.tableMembership064.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Include TV"))
        item = self.tableMembership064.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Antar (KM)"))
        item = self.tableMembership064.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Total Biaya"))
        self.editMember064.setText(_translate("MainWindow", "EDIT"))
        self.hpsMember064.setText(_translate("MainWindow", "DELETE"))
        self.lblTransaksiTitle.setText(_translate("MainWindow", "DATABASE PELANGGAN (MASTER)"))
        self.groupTransaksiTable.setTitle(_translate("MainWindow", "DATA TRANSAKSI KESELURUHAN"))
        item = self.tableTransaksi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pilih"))
        item = self.tableTransaksi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pelanggan"))
        item = self.tableTransaksi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipe PS"))
        item = self.tableTransaksi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Biaya"))
        self.btnKembaliTransaksi.setText(_translate("MainWindow", "KEMBALI"))
        self.btnEditPelangganDb.setText(_translate("MainWindow", "EDIT DATA PELANGGAN"))
        self.btnEditMembershipDb.setText(_translate("MainWindow", "EDIT DATA MEMBERSHIP"))
        self.menuApp.setTitle(_translate("MainWindow", "Beranda"))
        self.menuManage.setTitle(_translate("MainWindow", "Panel Admin"))
        self.actionLanding_Page.setText(_translate("MainWindow", "Landing Page"))
        self.actionDashboard.setText(_translate("MainWindow", "Dashboard Member"))
        self.actionMembership.setText(_translate("MainWindow", "Data Membership"))
        self.actionTransaksi.setText(_translate("MainWindow", "Database Pelanggan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
